framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: jte_test

        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            app.stats_cache:
                adapter: cache.adapter.redis
            app.reference_cache:
                adapter: cache.adapter.redis
