artprima_prometheus_metrics:
    namespace: app
    type: redis
    redis:
        host: redis
        port: 6379
    disable_default_promphp_metrics: true
    disable_default_metrics: true
    ignored_routes:
        - app_metrics
