{
 "title": "Main Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PHP Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"symfony\"}"
    }
   ]
  },
  {
   "title": "Messenger Queue Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_messenger_queue_messages" }
   ]
  },
  {
   "title": "App Performance (p90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "app_database_response_time_seconds{quantile=\"0.9\"}",
     "legendFormat": "DB Response Time (p90)"
    },
    {
     "expr": "app_doctrine_flush_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "Doctrine Flush (p90)"
    }
   ]
  },
  { "title": "Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "MySQL Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected"
    }
   ]
  },
  {
   "title": "MySQL Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "irate(mysql_global_status_questions[5m])",
     "legendFormat": "Queries/s"
    }
   ]
  }
 ]
}